### ISSUE TITLE
Allow variable escaping for PostgreSQL scripts

### ISSUE THREAD

**Issue by matkokostelic** [DbUp/dbup-postgresql#9]
If SQL script contains something like `$BODY$` (used in postgresql to create functions), exception happens:

`Upgrade failed due to an unexpected exception:
System.InvalidOperationException: Variable BODY has no value defined
at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.<>c__DisplayClass3_0.<ReplaceVariables>b__1(String name)
at DbUp.Support.SqlParser.Parse()
at DbUp.Engine.Preprocessors.VariableSubstitutionSqlParser.ReplaceVariables(IDictionary2 variables)
at DbUp.Engine.Preprocessors.VariableSubstitutionPreprocessor.Process(String contents)
at DbUp.Support.ScriptExecutor.PreprocessScriptContents(SqlScript script, IDictionary2 variables)
at DbUp.Support.ScriptExecutor.Execute(SqlScript script, IDictionary2 variables)
at DbUp.Engine.UpgradeEngine.PerformUpgrade()`

SQL script is like this:

`CREATE FUNCTION public.fn_something(
	b_id integer)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
   RETURN (
   select count(*) as something from sometable
	where id=b_id);
END
$BODY$;`

Any other idea than renaming `$BODY$` to something which will not be picked up as variable?

**Comment by droyad** [comment]
Duplicate of #1
